@MiPos.API_HostAddress = http://localhost:5015
@Host_Render = https://mipos-api-kpai.onrender.com

@MiPos.API_HostAddress = {{Host_Render}}

GET {{Host_Render}}/weatherforecast/
Accept: application/json

###
